# Generated by Django 5.0 on 2023-12-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuratApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
